version: '3.5'
services:
  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
      - .:/code
      - ./devtools/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - proxynet
  php:
    image: php:7-fpm
    volumes:
      - .:/code
      - ./devtools/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - proxynet
networks:
  proxynet: